name: Build and Deploy

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Deploy to GitHub Pages
        uses: jenkey2011/vuepress-deploy@master
        env:
          # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: Lookqiang/threeOne
          TARGET_BRANCH: main
          BUILD_SCRIPT: npm && npm run docs:build
          BUILD_DIR: docs/.vuepress/dist
