name: Build and Deploy

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest

     steps:
      - name: Checkout
        uses: actions/checkout@main
   
      - name: Deploy to GitHub Pages
        uses: Lookqiang/threeOne@main
        with:
          # 部署目录为 VuePress 的默认输出目录
          build_dir: docs/.vuepress/dist
        env:
          # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: Lookqiang/threeOne
          TARGET_BRANCH: main
          BUILD_SCRIPT: npm && npm run docs:build
          BUILD_DIR:  docs/.vuepress/dist
